### ISSUE TITLE
I can't see any source

### ISSUE THREAD

**Issue by mtugnoli** [dotnetbrightener/PDF-From-XML-Template-Generator#1]
I can't see any source...

Is it a dead project ?

It was a good idea !

**Comment by DotNetBrightener** [comment]
> I can't see any source...
> 
> Is it a dead project ?
> 
> It was a good idea !

Thank you for your interest in the project. I have been busy with parental responsibility and some other projects going on, so I have not resumed the project yet. Please stay tuned, I will publish more code when I have time.
